import { createContext, useContext, useState } from 'react';

export const LanguageContext = createContext({ lang: 'en', toggle: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const toggle = () => setLang(l => l === 'en' ? 'es' : 'en');
  return (
    <LanguageContext.Provider value={{ lang, toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const { lang } = useContext(LanguageContext);
  return lang;
}

export function useT() {
  const { lang } = useContext(LanguageContext);
  return (key) => {
    const parts = key.split('.');
    let node = translations[lang];
    for (const p of parts) {
      node = node?.[p];
      if (node === undefined) return key;
    }
    return node;
  };
}

/* ─────────────────────────────────────────────────────────────
   Full translation dictionary
───────────────────────────────────────────────────────────── */
const translations = {
  en: {
    nav: {
      brand:   'FinanceHub',
      car:     '🚗 Car Loan',
      home:    '🏠 Home Loan',
      budget:  '📝 Budget Planner',
      tax:     '💼 Net Income',
      cc:      '💳 Credit Card',
      amex:       '⭐ Referrals',
      retirement: '🏦 Retirement',
      langBtn: 'ES',
      langLabel: 'Español',
    },
    titles: {
      car:        'Car Loan Calculator',
      home:       'Home Loan Calculator',
      budget:     'Budget Planner',
      tax:        'Net Income After Taxes',
      cc:         'Credit Card Payoff',
      amex:       'Card Referrals',
      retirement: 'Retirement Calculator',
    },
    footer: 'FinanceHub · Educational estimates only · Not financial advice ·',

    car: {
      sub:          'Calculate your monthly payment and total cost for a vehicle purchase.',
      loanDetails:  'Loan Details',
      vehiclePrice: 'Vehicle Price',
      downPayment:  'Down Payment',
      tradeIn:      'Trade-In Value',
      interestRate: 'Interest Rate',
      loanTerm:     'Loan Term',
      months:       'months',
      yr:           'yr',
      yrs:          'yrs',
      paymentSummary: 'Payment Summary',
      monthlyPayment: 'Monthly Payment',
      forMonths:    'for {n} months',
      loanAmount:   'Loan Amount',
      totalInterest:'Total Interest',
      totalCost:    'Total Cost',
      includingDown:'including down',
      balanceOverTime: 'Balance Over Time',
      month:        'Month',
      balance:      'Balance',
      amortSched:   'Amortization Schedule',
      hideTable:    'Hide Table',
      showTable:    'Show Table',
      toggleHint:   'Toggle the table to see full month-by-month breakdown.',
      payment:      'Payment',
      principal:    'Principal',
      interest:     'Interest',
      extraPmt:     'Extra Monthly Payment',
      earlyPayoff:  'With Extra Payment',
      monthsSaved:  'Months Saved',
      interestSaved:'Interest Saved',
      paysOffIn:    'Pays off in {months} months',
    },

    home: {
      sub:            'Model your mortgage payment including taxes, insurance, and PMI.',
      mortgageDetails:'Mortgage Details',
      homePrice:      'Home Price',
      downPayment:    'Down Payment',
      interestRate:   'Interest Rate',
      loanTerm:       'Loan Term',
      years30:        '30 Years',
      years20:        '20 Years',
      years15:        '15 Years',
      years10:        '10 Years',
      propertyTax:    'Property Tax /mo',
      insurance:      'Insurance /mo',
      hoa:            'HOA /mo',
      pmi:            'PMI /mo',
      pmiHint:        'Est. {pmi}/mo at 0.8% annual rate',
      ltvWarning:     'LTV is {ltv}% — lenders typically require PMI above 80% LTV.',
      paymentBreakdown: 'Monthly Payment Breakdown',
      totalPITI:      'Total PITI /mo',
      pitiSub:        'principal + interest + escrow',
      piOnly:         'P&I Only',
      loanAmount:     'Loan Amount',
      totalInterest:  'Total Interest',
      equityGrowth:   'Equity Growth',
      equity:         'Equity',
      balance:        'Balance',
      amortSched:     'Amortization Schedule',
      hideTable:      'Hide Table',
      showTable:      'Show Table',
      toggleHint:     'Toggle the table to see full month-by-month breakdown.',
      month:          'Month',
      payment:        'Payment',
      principal:      'Principal',
      interest:       'Interest',
    },

    budget: {
      sub:           'Track your monthly income and expenses to find where your money goes.',
      monthlyIncome: 'Monthly Income',
      takeHome:      'Take-Home Income (after tax)',
      expenses:      'Expenses',
      addPlaceholder:'Add category…',
      add:           'Add',
      remove:        'Remove',
      summary:       'Summary',
      totalExpenses: 'Total Expenses',
      surplus:       'Surplus',
      deficit:       'Deficit',
      savingsRate:   'Savings Rate',
      savingsTarget: 'target: 20%+',
      overspend:     "You're spending {amt}/mo more than you earn. Review your expenses.",
      breakdown:     'Spending Breakdown',
      defaultCats:   ['Housing','Transportation','Groceries','Utilities','Dining Out','Healthcare','Entertainment','Savings','Clothing','Other'],
      rule2030:      '50/30/20 Rule',
      needs:         'Needs',
      wants:         'Wants',
      saves:         'Savings Goal',
      needsHint:     'Housing, utilities, groceries, healthcare, transport',
      wantsHint:     'Dining out, entertainment, clothing, misc',
      savingsHint:   'Savings, investments, emergency fund',
      ruleTarget:    'Target',
      ruleActual:    'Actual',
    },

    tax: {
      sub:          'Estimate your take-home pay after federal, state, and FICA taxes for 2024.',
      incomeAndFiling:'Income & Filing',
      grossIncome:  'Gross Annual Income',
      filingStatus: 'Filing Status',
      single:       'Single',
      married:      'Married Filing Jointly',
      hoh:          'Head of Household',
      state:        'State',
      preTaxDed:    'Pre-Tax Deductions',
      k401:         '401(k) Contribution',
      hsa:          'HSA Contribution',
      otherPreTax:  'Other Pre-Tax',
      takeHome:     'Take-Home Pay',
      annualNet:    'Annual Net',
      monthly:      'Monthly',
      biWeekly:     'Bi-Weekly',
      effectiveTax: 'Effective Tax Rate',
      ofGross:      'of gross income',
      fedTax:       'Federal Tax',
      socSec:       'Social Security',
      medicare:     'Medicare',
      stateTax:     'State Tax',
      netTakeHome:  'Net Take-Home',
      incomeBreakdown: 'Income Breakdown',
      brackets:     'Federal Tax Brackets (2024)',
      taxableIncome:'Taxable income: {taxable} (after {deduction} standard deduction)',
      taxed:        'taxed',
    },

    cc: {
      sub:          'See how long it takes to pay off credit card debt and how extra payments help.',
      cardDetails:  'Card Details',
      balance:      'Current Balance',
      apr:          'Annual Percentage Rate (APR)',
      monthlyPmt:   'Monthly Payment',
      extraPmt:     'Extra Monthly Payment',
      payoffScenarios: 'Payoff Scenarios',
      minPayment:   'Minimum Payment (~2% of balance)',
      payoffTime:   'Payoff Time',
      totalInterest:'Total Interest',
      totalPaid:    'Total Paid',
      atPayment:    'At {amt}/mo',
      withExtra:    '✨ With +{extra}/mo extra = {total}/mo',
      interestSaved:'Interest Saved',
      monthsSaved:  'Months Saved',
      noPayment:    "Payment doesn't cover interest!",
      lowPayment:   "Monthly payment of {pmt} doesn't cover the interest charge of {interest}/mo. Increase your payment.",
      keyStats:     'Key Stats',
      dailyInterest:'Daily Interest',
      monthlyInterest:'Monthly Interest',
      annualInterest: 'Annual Interest',
      balanceOverTime:'Balance Over Time',
      basePayment:  'Base Payment',
      extraPayment: 'Extra Payment',
      yr:           'y',
      mo:           'm',
    },

    amex: {
      badge:        '⭐ American Express Referrals',
      heroTitle:    'Refer Friends. Earn Points.',
      heroBody:     'Share your Amex referral links and earn bonus Membership Rewards points or statement credits each time a friend is approved. It\'s one of the easiest ways to accelerate your rewards balance.',
      yourLink:     'Your Referral Link',
      linkDesc:     'Log in to your Amex account → "Refer a Friend" → paste your personal link below to share it easily.',
      linkPlaceholder: 'Paste your Amex referral link here…',
      copyBtn:      '📋 Copy Link',
      copiedBtn:    '✓ Copied!',
      linkTip:      'Tip: Your referral link is unique to you and the specific card. Get a separate link for each card you want to refer.',
      cardsTitle:   'Cards You Can Refer',
      cardsSub:     'You can only refer for cards you currently hold. Click "Refer a Friend" on amex.com after selecting the card.',
      welcomeOffer: 'Welcome Offer',
      welcomeBonus: 'Welcome Bonus:',
      bestFor:      'Best for:',
      referNote:    '',
      getLink:      'Get Your Referral Link →',
      tipsTitle:    '💡 Referral Tips',
      tips: [
        { icon:'🎯', title:'Get a unique link per card',  desc:'Each card you hold has its own referral link. Go to Refer a Friend on amex.com and select the specific card.' },
        { icon:'📣', title:'Share across channels',       desc:'Post to social media, text friends, or add to your email signature. More reaches = more approvals.' },
        { icon:'⏱', title:'Points post after approval',  desc:"Your referral bonus usually arrives within 8–12 weeks after your friend's application is approved." },
      ],
    },

    retirement: {
      sub:              'Project your nest egg and see if you\'re on track for a comfortable retirement.',
      inputs:           'Your Details',
      currentAge:       'Current Age',
      retirementAge:    'Retirement Age',
      currentSavings:   'Current Savings',
      monthlyContrib:   'Monthly Contribution',
      annualReturn:     'Expected Annual Return',
      annualReturnSub:  '(S&P 500 historical avg ~10%)',
      inflationRate:    'Inflation Rate',
      inflationSub:     'for real-value estimate',
      desiredIncome:    'Desired Annual Income in Retirement',
      desiredIncomeSub: 'in today\'s dollars',
      results:          'Projected at Retirement',
      projectedSavings: 'Projected Savings',
      atAge:            'at age {age}',
      yearsToRetire:    'Years to Retirement',
      totalContribs:    'Total Contributions',
      totalGrowth:      'Investment Growth',
      monthlyInRetirement: 'Est. Monthly Income',
      monthlyInRetirementSub: 'over {years} yr retirement',
      onTrack:          '✅ On Track',
      onTrackDesc:      'Your projected savings of {projected} exceeds your target of {target}. Great work!',
      offTrack:         '⚠ Needs Attention',
      offTrackDesc:     'You\'re {gap} short of your {target} target. Consider increasing contributions or adjusting your retirement age.',
      shortfall:        'Shortfall',
      surplus:          'Surplus',
      target:           'Savings Target',
      targetSub:        'to fund {years} yrs at {income}/yr',
      growthChart:      'Savings Growth Over Time',
      age:              'Age',
      savings:          'Savings',
      contributions:    'Contributions',
      growth:           'Growth',
      milestone25:      '25% Milestone',
      milestone50:      '50% Milestone',
      milestone75:      '75% Milestone',
      milestones:       'Key Milestones',
      retireIn:         'Retire in {n} years',
      globalSettings:   'Global Settings',
      accounts:         'Retirement Accounts',
      addAccount:       'Add Account',
      removeAccount:    'Remove Account',
      accountBalance:   'Current Balance',
      accountContrib:   'Monthly Contribution',
      accountReturn:    'Expected Annual Return',
      projectedAt:      'Projected at Age {age}',
      combinedTotal:    'Combined Total',
      accountsSummary:  'Account Breakdown',
      noAccounts:       'Add at least one account to see projections.',
      total:            'Total',
      socialSecurity:   'Monthly Social Security Estimate',
      socialSecuritySub:'reduces required portfolio size',
    },
  },

  /* ── SPANISH ───────────────────────────────────────────── */
  es: {
    nav: {
      brand:    'FinanceHub',
      car:      '🚗 Préstamo Auto',
      home:     '🏠 Préstamo Casa',
      budget:   '📝 Presupuesto',
      tax:      '💼 Ingreso Neto',
      cc:       '💳 Tarjeta Crédito',
      amex:       '⭐ Referencias',
      retirement: '🏦 Jubilación',
      langBtn:  'EN',
      langLabel:'English',
    },
    titles: {
      car:        'Calculadora de Préstamo de Auto',
      home:       'Calculadora de Préstamo Hipotecario',
      budget:     'Planificador de Presupuesto',
      tax:        'Ingreso Neto Después de Impuestos',
      cc:         'Pago de Tarjeta de Crédito',
      amex:       'Referencias de Tarjetas',
      retirement: 'Calculadora de Jubilación',
    },
    footer: 'FinanceHub · Solo estimaciones educativas · No es asesoría financiera ·',

    car: {
      sub:          'Calcula tu pago mensual y el costo total de la compra de un vehículo.',
      loanDetails:  'Detalles del Préstamo',
      vehiclePrice: 'Precio del Vehículo',
      downPayment:  'Pago Inicial',
      tradeIn:      'Valor de Intercambio',
      interestRate: 'Tasa de Interés',
      loanTerm:     'Plazo del Préstamo',
      months:       'meses',
      yr:           'año',
      yrs:          'años',
      paymentSummary: 'Resumen del Pago',
      monthlyPayment: 'Pago Mensual',
      forMonths:    'por {n} meses',
      loanAmount:   'Monto del Préstamo',
      totalInterest:'Interés Total',
      totalCost:    'Costo Total',
      includingDown:'incluyendo inicial',
      balanceOverTime: 'Saldo con el Tiempo',
      month:        'Mes',
      balance:      'Saldo',
      amortSched:   'Tabla de Amortización',
      hideTable:    'Ocultar Tabla',
      showTable:    'Ver Tabla',
      toggleHint:   'Muestra la tabla para ver el desglose mes a mes.',
      payment:      'Pago',
      principal:    'Capital',
      interest:     'Interés',
      extraPmt:     'Pago Mensual Adicional',
      earlyPayoff:  'Con Pago Adicional',
      monthsSaved:  'Meses Ahorrados',
      interestSaved:'Interés Ahorrado',
      paysOffIn:    'Se paga en {months} meses',
    },

    home: {
      sub:            'Modela tu pago hipotecario incluyendo impuestos, seguro y PMI.',
      mortgageDetails:'Detalles Hipotecarios',
      homePrice:      'Precio de la Vivienda',
      downPayment:    'Pago Inicial',
      interestRate:   'Tasa de Interés',
      loanTerm:       'Plazo del Préstamo',
      years30:        '30 Años',
      years20:        '20 Años',
      years15:        '15 Años',
      years10:        '10 Años',
      propertyTax:    'Impuesto Predial /mes',
      insurance:      'Seguro /mes',
      hoa:            'HOA /mes',
      pmi:            'PMI /mes',
      pmiHint:        'Est. {pmi}/mes (tasa anual 0.8%)',
      ltvWarning:     'El LTV es {ltv}% — los prestamistas suelen exigir PMI si supera el 80%.',
      paymentBreakdown: 'Desglose del Pago Mensual',
      totalPITI:      'PITI Total /mes',
      pitiSub:        'capital + interés + depósito en garantía',
      piOnly:         'Solo C&I',
      loanAmount:     'Monto del Préstamo',
      totalInterest:  'Interés Total',
      equityGrowth:   'Crecimiento del Patrimonio',
      equity:         'Patrimonio',
      balance:        'Saldo',
      amortSched:     'Tabla de Amortización',
      hideTable:      'Ocultar Tabla',
      showTable:      'Ver Tabla',
      toggleHint:     'Muestra la tabla para ver el desglose mes a mes.',
      month:          'Mes',
      payment:        'Pago',
      principal:      'Capital',
      interest:       'Interés',
    },

    budget: {
      sub:           'Registra tus ingresos y gastos mensuales para saber a dónde va tu dinero.',
      monthlyIncome: 'Ingresos Mensuales',
      takeHome:      'Ingreso Neto (después de impuestos)',
      expenses:      'Gastos',
      addPlaceholder:'Agregar categoría…',
      add:           'Agregar',
      remove:        'Eliminar',
      summary:       'Resumen',
      totalExpenses: 'Gastos Totales',
      surplus:       'Superávit',
      deficit:       'Déficit',
      savingsRate:   'Tasa de Ahorro',
      savingsTarget: 'meta: 20%+',
      overspend:     'Estás gastando {amt}/mes más de lo que ganas. Revisa tus gastos.',
      breakdown:     'Desglose de Gastos',
      defaultCats:   ['Vivienda','Transporte','Comestibles','Servicios','Restaurantes','Salud','Entretenimiento','Ahorros','Ropa','Otros'],
      rule2030:      'Regla 50/30/20',
      needs:         'Necesidades',
      wants:         'Gustos',
      saves:         'Meta de Ahorro',
      needsHint:     'Vivienda, servicios, comestibles, salud, transporte',
      wantsHint:     'Restaurantes, entretenimiento, ropa, varios',
      savingsHint:   'Ahorro, inversiones, fondo de emergencia',
      ruleTarget:    'Meta',
      ruleActual:    'Real',
    },

    tax: {
      sub:          'Estima tu pago neto después de impuestos federales, estatales y del FICA para 2024.',
      incomeAndFiling:'Ingresos y Estado Civil',
      grossIncome:  'Ingreso Bruto Anual',
      filingStatus: 'Estado de Declaración',
      single:       'Soltero/a',
      married:      'Casado/a Declaración Conjunta',
      hoh:          'Jefe/a de Hogar',
      state:        'Estado',
      preTaxDed:    'Deducciones Pre-Impuestos',
      k401:         'Aportación 401(k)',
      hsa:          'Aportación HSA',
      otherPreTax:  'Otros Pre-Impuestos',
      takeHome:     'Pago Neto',
      annualNet:    'Neto Anual',
      monthly:      'Mensual',
      biWeekly:     'Quincenal',
      effectiveTax: 'Tasa Efectiva de Impuesto',
      ofGross:      'del ingreso bruto',
      fedTax:       'Impuesto Federal',
      socSec:       'Seguro Social',
      medicare:     'Medicare',
      stateTax:     'Impuesto Estatal',
      netTakeHome:  'Neto a Recibir',
      incomeBreakdown: 'Desglose de Ingresos',
      brackets:     'Tramos del Impuesto Federal (2024)',
      taxableIncome:'Ingreso gravable: {taxable} (después de deducción estándar de {deduction})',
      taxed:        'gravado',
    },

    cc: {
      sub:          'Mira cuánto tiempo tarda en pagarse una deuda de tarjeta de crédito y cómo ayudan los pagos extra.',
      cardDetails:  'Detalles de la Tarjeta',
      balance:      'Saldo Actual',
      apr:          'Tasa Anual (APR)',
      monthlyPmt:   'Pago Mensual',
      extraPmt:     'Pago Mensual Adicional',
      payoffScenarios: 'Escenarios de Pago',
      minPayment:   'Pago Mínimo (~2% del saldo)',
      payoffTime:   'Tiempo para Liquidar',
      totalInterest:'Interés Total',
      totalPaid:    'Total Pagado',
      atPayment:    'Con {amt}/mes',
      withExtra:    '✨ Con +{extra}/mes extra = {total}/mes',
      interestSaved:'Interés Ahorrado',
      monthsSaved:  'Meses Ahorrados',
      noPayment:    '¡El pago no cubre el interés!',
      lowPayment:   'El pago de {pmt} no cubre el cargo de interés de {interest}/mes. Aumenta tu pago.',
      keyStats:     'Datos Clave',
      dailyInterest:'Interés Diario',
      monthlyInterest:'Interés Mensual',
      annualInterest: 'Interés Anual',
      balanceOverTime:'Saldo con el Tiempo',
      basePayment:  'Pago Base',
      extraPayment: 'Pago Adicional',
      yr:           'a',
      mo:           'm',
    },

    amex: {
      badge:        '⭐ Referencias de American Express',
      heroTitle:    'Recomienda Amigos. Gana Puntos.',
      heroBody:     'Comparte tus enlaces de referencia Amex y gana puntos de bonificación o créditos de estado de cuenta cada vez que un amigo sea aprobado. Es una de las formas más fáciles de acelerar tu saldo de recompensas.',
      yourLink:     'Tu Enlace de Referencia',
      linkDesc:     'Inicia sesión en tu cuenta Amex → "Recomienda a un Amigo" → pega tu enlace personal a continuación para compartirlo fácilmente.',
      linkPlaceholder: 'Pega tu enlace de referencia Amex aquí…',
      copyBtn:      '📋 Copiar Enlace',
      copiedBtn:    '✓ ¡Copiado!',
      linkTip:      'Consejo: Tu enlace de referencia es único para ti y para la tarjeta específica. Obtén un enlace distinto por cada tarjeta que desees referir.',
      cardsTitle:   'Tarjetas que Puedes Referir',
      cardsSub:     'Solo puedes referir tarjetas que actualmente tengas. Haz clic en "Recomienda a un Amigo" en amex.com después de seleccionar la tarjeta.',
      welcomeOffer: 'Oferta de Bienvenida',
      welcomeBonus: 'Bono de Bienvenida:',
      bestFor:      'Ideal para:',
      referNote:    '',
      getLink:      'Obtén tu Enlace de Referencia →',
      tipsTitle:    '💡 Consejos de Referencia',
      tips: [
        { icon:'🎯', title:'Un enlace único por tarjeta',   desc:'Cada tarjeta que tengas tiene su propio enlace de referencia. Ve a "Recomienda a un Amigo" en amex.com y selecciona la tarjeta específica.' },
        { icon:'📣', title:'Comparte en múltiples canales', desc:'Publica en redes sociales, envía mensajes a amigos o agrégalo a tu firma de correo. Más alcance = más aprobaciones.' },
        { icon:'⏱', title:'Los puntos llegan tras aprobación', desc:'Tu bono de referencia suele llegar entre 8 y 12 semanas después de que la solicitud de tu amigo sea aprobada.' },
      ],
    },

    retirement: {
      sub:              'Proyecta tu fondo de retiro y comprueba si vas por buen camino.',
      inputs:           'Tus Datos',
      currentAge:       'Edad Actual',
      retirementAge:    'Edad de Jubilación',
      currentSavings:   'Ahorros Actuales',
      monthlyContrib:   'Aportación Mensual',
      annualReturn:     'Rendimiento Anual Esperado',
      annualReturnSub:  '(promedio histórico S&P 500 ~10%)',
      inflationRate:    'Tasa de Inflación',
      inflationSub:     'para estimación en valor real',
      desiredIncome:    'Ingreso Anual Deseado en Jubilación',
      desiredIncomeSub: 'en dólares de hoy',
      results:          'Proyección al Retiro',
      projectedSavings: 'Ahorros Proyectados',
      atAge:            'a los {age} años',
      yearsToRetire:    'Años para Jubilarse',
      totalContribs:    'Aportaciones Totales',
      totalGrowth:      'Crecimiento por Inversión',
      monthlyInRetirement: 'Ingreso Mensual Est.',
      monthlyInRetirementSub: 'durante {years} años de retiro',
      onTrack:          '✅ En Buen Camino',
      onTrackDesc:      'Tu ahorro proyectado de {projected} supera tu meta de {target}. ¡Excelente trabajo!',
      offTrack:         '⚠ Requiere Atención',
      offTrackDesc:     'Te faltan {gap} para alcanzar tu meta de {target}. Considera aumentar tus aportaciones o ajustar tu edad de jubilación.',
      shortfall:        'Déficit',
      surplus:          'Superávit',
      target:           'Meta de Ahorro',
      targetSub:        'para {years} años a {income}/año',
      growthChart:      'Crecimiento del Ahorro con el Tiempo',
      age:              'Edad',
      savings:          'Ahorros',
      contributions:    'Aportaciones',
      growth:           'Crecimiento',
      milestone25:      'Hito 25%',
      milestone50:      'Hito 50%',
      milestone75:      'Hito 75%',
      milestones:       'Hitos Clave',
      retireIn:         'Jubilarse en {n} años',
      globalSettings:   'Configuración General',
      accounts:         'Cuentas de Jubilación',
      addAccount:       'Agregar Cuenta',
      removeAccount:    'Eliminar Cuenta',
      accountBalance:   'Saldo Actual',
      accountContrib:   'Aportación Mensual',
      accountReturn:    'Rendimiento Anual Esperado',
      projectedAt:      'Proyectado a los {age} años',
      combinedTotal:    'Total Combinado',
      accountsSummary:  'Desglose de Cuentas',
      noAccounts:       'Agrega al menos una cuenta para ver las proyecciones.',
      total:            'Total',
      socialSecurity:   'Estimado Mensual del Seguro Social',
      socialSecuritySub:'reduce el tamaño requerido del portafolio',
    },
  },
};
