import { createContext, useContext, useState } from 'react';

export const LanguageContext = createContext({ lang: 'en', toggle: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const toggle = () => setLang(l => l === 'en' ? 'es' : 'en');
  return (
    <LanguageContext.Provider value={{ lang, toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const { lang } = useContext(LanguageContext);
  return lang;
}

export function useT() {
  const { lang } = useContext(LanguageContext);
  return (key) => {
    const parts = key.split('.');
    let node = translations[lang];
    for (const p of parts) {
      node = node?.[p];
      if (node === undefined) return key;
    }
    return node;
  };
}

/* ─────────────────────────────────────────────────────────────
   Full translation dictionary
───────────────────────────────────────────────────────────── */
const translations = {
  en: {
    nav: {
      brand:   'FinanceHub',
      car:     '🚗 Car Loan',
      home:    '🏠 Home Loan',
      budget:  '📝 Budget Planner',
      tax:     '💼 Net Income',
      cc:      '💳 Credit Card',
      amex:        '⭐ Referrals',
      retirement:  '🏦 Retirement',
      personalLoan: '📋 Personal Loan',
      groupLoans:       'Loans',
      groupPlanning:    'Planning',
      groupIncome:      'Income',
      groupInvestments: 'Investments',
      groupCards:       'Cards',
      groupMilitary:    'Military',
      bills:         '📅 Bill Tracker',
      debt:          '💳 Debt Tracker',
      emergency:     '🆘 Emergency Fund',
      savings:       '🎯 Savings Goals',
      subscriptions: '📱 Subscriptions',
      military:      '🎖 Military Pay',
      langBtn: 'ES',
      langLabel: 'Español',
    },
    titles: {
      landing:       'Home',
      car:           'Car Loan Calculator',
      home:          'Home Loan Calculator',
      budget:        'Budget Planner',
      tax:           'Net Income After Taxes',
      cc:            'Credit Card Payoff',
      amex:          'Card Referrals',
      retirement:    'Retirement Calculator',
      personalLoan:  'Personal Loan Calculator',
      bills:         'Bill Tracker',
      debt:          'Debt Tracker',
      emergency:     'Emergency Fund Calculator',
      savings:       'Savings Goals',
      subscriptions: 'Subscription Tracker',
      military:      'Military Pay Calculator',
    },
    footer: 'FinanceHub · Educational estimates only · Not financial advice ·',

    landing: {
      badge:          '💰 Free Financial Tools',
      heroTitle:      'Take Control of Your Finances',
      heroSub:        'Free calculators built by real people who learned the hard way. No ads, no upsells — just honest tools that help you make smarter decisions.',
      heroCta1:       'Explore Calculators',
      heroCta2:       'Our Recommended Cards',
      toolsTitle:     'All Our Calculators',
      toolsSub:       'Find the right tool for whatever financial question you\'re facing.',
      openTool:       'Open calculator',
      descCar:        'Calculate monthly payments, total interest, and true cost of ownership including insurance, maintenance, and depreciation.',
      descHome:       'Model your full mortgage payment with taxes, insurance, and PMI — and watch your equity grow over time.',
      descBudget:     'Your complete financial planning hub — track income and expenses, manage bills, debt payoff, emergency fund, savings goals, and subscriptions all in one place.',
      descTax:        'Estimate your real take-home pay after federal, state, and FICA taxes for any income or filing status.',
      descCc:         'See how long it takes to pay off credit card debt, and how extra payments can save you thousands.',
      descAmex:       'Cards we personally use and trust — apply through our referral links and get a welcome bonus.',
      descRetirement: 'Project your nest egg across multiple retirement accounts and see if you\'re on track.',
      descPersonalLoan:'Understand the true cost of personal loans, spot predatory lenders, and compare rates by credit score.',
      descBills:         'Track recurring bills with a calendar view, color-coded categories, and 7-day due alerts.',
      descDebt:          'Compare Avalanche vs Snowball payoff strategies side by side and see your debt-free date.',
      descEmergency:     'Calculate your 3 and 6-month emergency fund targets based on your real expenses and track progress.',
      descSavings:       'Set multiple savings goals with target dates, progress bars, and on-track status indicators.',
      descSubscriptions: 'List all your subscriptions, see your total monthly and annual spend, and spot the priciest ones.',
      descMilitary:      'Calculate military pay including base pay by rank/YOS, BAH by location, BAS, and drill pay.',
      catLoans:        'Loans',
      catIncome:       'Income & Tax',
      catPlanning:     'Planning & Budgeting',
      catInvestments:  'Investments',
      catCards:        'Cards & Rewards',
      trustFree:       '100% Free',
      trustPrivate:    'Fully Private',
      trustNoAds:      'No Ads',
      trustNoSignup:   'No Sign-up',
      viewAll:         'View all 14 tools',
      viewFeatured:    'Show featured only',
      cardsTitle:     'Credit Cards We Actually Use',
      cardsSub:       'We earn points and cash back on cards we\'d recommend to anyone. Apply through our referral links for a welcome bonus.',
      aboutTitle:     'Built by Real People',
      aboutQuote:     '"We built FinanceHub because we know what it feels like to make costly financial mistakes."',
      aboutBody1:     'Between navigating a new country, learning the US credit system, and figuring it out as we went — we wish we\'d had a tool like this. Every calculator here is the resource we needed and couldn\'t find.',
      aboutBody2:     'Now we want to help others make smarter financial decisions from the start. Everything is free, private, and runs entirely in your browser — no sign-up, no ads, no catch.',
      statTools:      'Free calculators',
      statFree:       'Free. Always.',
      statAds:        'Ads or upsells',
      ctaTitle:       'Ready to Take Control?',
      ctaSub:         'Every tool is free and private. Nothing is stored on a server. Start wherever you are.',
      navHome:        'Home',
    },

    car: {
      sub:          'Calculate your monthly payment and total cost for a vehicle purchase.',
      loanDetails:  'Loan Details',
      vehiclePrice: 'Vehicle Price',
      downPayment:  'Down Payment',
      tradeIn:      'Trade-In Value',
      interestRate: 'Interest Rate',
      loanTerm:     'Loan Term',
      months:       'months',
      yr:           'yr',
      yrs:          'yrs',
      paymentSummary: 'Payment Summary',
      monthlyPayment: 'Monthly Payment',
      forMonths:    'for {n} months',
      loanAmount:   'Loan Amount',
      totalInterest:'Total Interest',
      totalCost:    'Total Cost',
      includingDown:'including down',
      balanceOverTime: 'Balance Over Time',
      month:        'Month',
      balance:      'Balance',
      amortSched:   'Amortization Schedule',
      hideTable:    'Hide Table',
      showTable:    'Show Table',
      toggleHint:   'Toggle the table to see full month-by-month breakdown.',
      payment:      'Payment',
      principal:    'Principal',
      interest:     'Interest',
      extraPmt:     'Extra Monthly Payment',
      earlyPayoff:  'With Extra Payment',
      monthsSaved:  'Months Saved',
      interestSaved:'Interest Saved',
      paysOffIn:    'Pays off in {months} months',
      vehicles:     'Your Vehicles',
      addVehicle:   'Add Vehicle',
      removeVehicle:'Remove Vehicle',
      vehicleName:  'Vehicle Name',
      combinedMonthly: 'Combined Monthly Payment',
      noVehicles:   'Add at least one vehicle to see calculations.',

      lookupTitle:  'Vehicle Lookup',
      lookupOptional:'(optional)',
      newVehicle:   'New Vehicle',
      usedVehicle:  'Used Vehicle',
      make:         'Make',
      model:        'Model',
      trim:         'Trim',
      year:         'Model Year',
      mileage:      'Current Mileage',
      condition:    'Condition',
      condExcellent:'Excellent',
      condGood:     'Good',
      condFair:     'Fair',
      condPoor:     'Poor',
      selectMake:   '— Select Make —',
      selectModel:  '— Select Model —',
      selectTrim:   '— Select Trim —',
      msrpBase:     'Base MSRP',
      marketValue:  'Current Market Value',
      futureValue:  'Value at Payoff',
      depreciationDuring: 'Depreciation During Loan',
      insuranceEst: 'Est. Annual Insurance',
      maintenanceEst:'Est. Annual Maintenance',
      perYear:      '/year',
      tcoTitle:     'Total Cost of Ownership',
      tcoLoanCost:  'Loan Payments',
      tcoInsurance: 'Insurance (est.)',
      tcoInsuranceActual: 'Insurance (actual)',
      tcoMaintenance:'Maintenance (est.)',
      tcoDeprec:    'Depreciation',
      tcoGrandTotal:'Grand Total',
      tcoOver:      'over {n} months',
      upsideDown:   '⚠ Upside-Down Loan',
      upsideDownDesc:"Your loan amount ({loan}) exceeds the car's current market value ({value}). You owe more than the car is worth.",
      actualInsuranceLabel:      'My actual monthly insurance:',
      actualInsurancePlaceholder:'e.g. 150',
      actualInsuranceUsed:       'Using your actual insurance cost',
    },

    home: {
      sub:            'Model your mortgage payment including taxes, insurance, and PMI.',
      mortgageDetails:'Mortgage Details',
      homePrice:      'Home Price',
      downPayment:    'Down Payment',
      interestRate:   'Interest Rate',
      loanTerm:       'Loan Term',
      years30:        '30 Years',
      years20:        '20 Years',
      years15:        '15 Years',
      years10:        '10 Years',
      propertyTax:    'Property Tax /mo',
      insurance:      'Insurance /mo',
      hoa:            'HOA /mo',
      pmi:            'PMI /mo',
      pmiHint:        'Auto-calculated at 0.8% annual rate. Edit to override.',
      ltvWarning:     'LTV is {ltv}% — PMI auto-added. Removed when LTV reaches 80%.',
      extraPmt:       'Extra Monthly Payment',
      withExtraPayoff:'With Extra Payment',
      monthsSaved:    'Months Saved',
      interestSaved:  'Interest Saved',
      paysOffIn:      'Pays off in {months} months',
      paymentBreakdown: 'Monthly Payment Breakdown',
      totalPITI:      'Total PITI /mo',
      pitiSub:        'principal + interest + escrow',
      piOnly:         'P&I Only',
      loanAmount:     'Loan Amount',
      totalInterest:  'Total Interest',
      equityGrowth:   'Equity Growth',
      equity:         'Equity',
      balance:        'Balance',
      amortSched:     'Amortization Schedule',
      hideTable:      'Hide Table',
      showTable:      'Show Table',
      toggleHint:     'Toggle the table to see full month-by-month breakdown.',
      month:          'Month',
      payment:        'Payment',
      principal:      'Principal',
      interest:       'Interest',
    },

    budget: {
      sub:           'Track your monthly income and expenses to find where your money goes.',
      monthlyIncome: 'Monthly Income',
      takeHome:      'Take-Home Income (after tax)',
      expenses:      'Expenses',
      addPlaceholder:'Add category…',
      add:           'Add',
      remove:        'Remove',
      summary:       'Summary',
      totalExpenses: 'Total Expenses',
      surplus:       'Surplus',
      deficit:       'Deficit',
      savingsRate:   'Savings Rate',
      savingsTarget: 'target: 20%+',
      overspend:     "You're spending {amt}/mo more than you earn. Review your expenses.",
      breakdown:     'Spending Breakdown',
      defaultCats:   ['Housing','Transportation','Groceries','Utilities','Dining Out','Healthcare','Entertainment','Savings','Clothing','Other'],
      rule2030:      '50/30/20 Rule',
      needs:         'Needs',
      wants:         'Wants',
      saves:         'Savings Goal',
      needsHint:     'Housing, utilities, groceries, healthcare, transport',
      wantsHint:     'Dining out, entertainment, clothing, misc',
      savingsHint:   'Savings, investments, emergency fund',
      ruleTarget:    'Target',
      ruleActual:    'Actual',

      tab_overview:  'Overview',
      tab_expenses:  'Expenses',
      tab_calendar:  'Calendar',
      tab_networth:  'Net Worth',
      totalSpent:    'Total Spent',
      thisMonth:     'This Month',
      onTrack:       'On Track',
      overBudget:    'Over Budget',
      setBudget:     'Set budget limit',
      of:            'of',
      addCategory:   'Add Category',
      categoryName:  'Category name',
      addExpense:    'Add Expense',
      date:          'Date',
      description:   'Description',
      descPlaceholder:'e.g. Rent, Gas, Netflix',
      amount:        'Amount',
      category:      'Category',
      recentExpenses:'Recent Expenses',
      noExpenses:    'No expenses yet. Add one in the Expenses tab.',
      insightsTitle: 'Spending Insights',
      insightHousing:"You're spending {pct}% on housing — above the recommended 30%.",
      insightDining: 'Dining out is {pct}% of your income. Cooking more meals can help.',
      insightSavings:"You're saving {pct}% of income. The goal is 20% or more.",
      insightGreat:  "Your spending looks healthy! You're on track across categories.",
      insightOverspent:"You're over budget in {n} {n, plural, one{category} other{categories}}. Review your spending.",
      netWorthTotal: 'Total Net Worth',
      assets:        'Assets',
      liabilities:   'Liabilities',
      assetName:     'e.g. Savings Account',
      liabilityName: 'e.g. Car Loan',
      total:         'Total',
      catNames: {
        housing:       'Housing',
        transport:     'Transportation',
        groceries:     'Groceries',
        utilities:     'Utilities',
        dining:        'Dining Out',
        healthcare:    'Healthcare',
        entertainment: 'Entertainment',
        savings:       'Savings',
        clothing:      'Clothing',
        other:         'Other',
      },

      tab_bills:         'Bills',
      tab_debt:          'Debt',
      tab_emergency:     'Emergency',
      tab_savings:       'Goals',
      tab_subscriptions: 'Subs',
      tab_import:        'Import CSV',
      importTitle:       'Import Bank Statement',
      importDesc:        'Upload a CSV file downloaded from your bank or credit card provider. Transactions are auto-categorized and duplicates are skipped.',
      dropzoneText:      'Click or drag a CSV or PDF file here',
      supportedBanks:    'Chase · Bank of America · Capital One · Discover · American Express — CSV or PDF',
      detected:          'Detected Bank',
      unknownBank:       'Generic CSV',
      totalTransactions: 'Total Rows',
      newTransactions:   'New',
      duplicatesSkipped: 'Duplicates',
      importByCategory:  'Category Totals to Import',
      importPreview:     'Preview Transactions',
      selectAll:         'Select All',
      deselectAll:       'Deselect All',
      cancel:            'Cancel',
      importBtn:         'Import {n} Transactions',
      importSuccess:     '{n} Transactions Added',
      importSuccessDesc: 'Your transactions have been saved. View them in the Expenses tab.',
      importAnother:     'Import Another File',
      viewHistory:       'View Transaction History',
      parseError:        'Could not read this file. Make sure it is a valid CSV or PDF exported from a supported bank.',
      notCsvError:       'Please upload a .csv file.',
      notFileError:      'Please upload a .csv or .pdf bank statement file.',
      pdfNote:           'PDF parsing is best-effort. If transactions are missing, try the CSV export instead.',
      duplicate:         'Duplicate',
      history:           'Transaction History',
      transactions:      'transactions',
      noHistory:         'No transactions yet. Add one or import a bank CSV.',
      moreRows:          'more rows — scroll table to see all',
      importHowTo:       'Chase: Account → Download Account Activity → CSV. BofA: Statements → Download → CSV format. Capital One: Transactions → Download. Discover: Manage → Download Transactions. Amex: Statements → Export.',
      orImportHint:      'Have a bank CSV?',
      recentInCat:       'Recent',
    },

    tax: {
      sub:          'Estimate your take-home pay after federal, state, and FICA taxes for 2024.',
      incomeAndFiling:'Income & Filing',
      grossIncome:  'Gross Annual Income',
      filingStatus: 'Filing Status',
      single:       'Single',
      married:      'Married Filing Jointly',
      hoh:          'Head of Household',
      state:        'State',
      preTaxDed:    'Pre-Tax Deductions',
      k401:         '401(k) Contribution',
      hsa:          'HSA Contribution',
      otherPreTax:  'Other Pre-Tax',
      takeHome:     'Take-Home Pay',
      annualNet:    'Annual Net',
      monthly:      'Monthly',
      biWeekly:     'Bi-Weekly',
      effectiveTax: 'Effective Tax Rate',
      ofGross:      'of gross income',
      fedTax:       'Federal Tax',
      socSec:       'Social Security',
      medicare:     'Medicare',
      stateTax:     'State Tax',
      netTakeHome:  'Net Take-Home',
      incomeBreakdown: 'Income Breakdown',
      brackets:     'Federal Tax Brackets (2025)',
      dualIncome:   'Dual Income Household',
      earner1:      'Earner 1',
      earner2:      'Earner 2',
      householdTotal:'Household Combined',
      enableDual:   'Add Second Earner',
      combinedNet:  'Combined Net',
      taxableIncome:'Taxable income: {taxable} (after {deduction} standard deduction)',
      taxed:        'taxed',
      civilianMode: 'Civilian',
      militaryMode: 'Military Pay',
      milInputs:    'Military Information',
      serviceType:  'Service Type',
      activeDuty:   'Active Duty',
      guardReserve: 'Guard / Reserve',
      milBahArea:   'Duty Station Cost Area',
      milPreTax:    'Pre-Tax Deductions (TSP)',
      drillSchedule:'Drill Schedule',
      annualTrainingDays: 'Annual Training Days',
      milGrossPay:  'Military Gross Pay',
      taxableLabel: 'Taxable',
      taxFreeLabel: 'Tax-Free',
      milTotalGross:'Total Gross Compensation',
      milTaxNote:   'BAH and BAS are tax-free allowances',
      milAnnualGross:'Annual Gross',
      ofBasePay:    'of base pay',
      milOnBasePay: 'Federal tax calculated on base pay only — BAH and BAS are not taxed',
    },

    cc: {
      sub:          'See how long it takes to pay off credit card debt and how extra payments help.',
      cardDetails:  'Card Details',
      balance:      'Current Balance',
      apr:          'Annual Percentage Rate (APR)',
      monthlyPmt:   'Monthly Payment',
      extraPmt:     'Extra Monthly Payment',
      payoffScenarios: 'Payoff Scenarios',
      minPayment:   'Minimum Payment (~2% of balance)',
      payoffTime:   'Payoff Time',
      totalInterest:'Total Interest',
      totalPaid:    'Total Paid',
      atPayment:    'At {amt}/mo',
      withExtra:    '✨ With +{extra}/mo extra = {total}/mo',
      interestSaved:'Interest Saved',
      monthsSaved:  'Months Saved',
      noPayment:    "Payment doesn't cover interest!",
      lowPayment:   "Monthly payment of {pmt} doesn't cover the interest charge of {interest}/mo. Increase your payment.",
      keyStats:     'Key Stats',
      dailyInterest:'Daily Interest',
      monthlyInterest:'Monthly Interest',
      annualInterest: 'Annual Interest',
      balanceOverTime:'Balance Over Time',
      basePayment:  'Base Payment',
      extraPayment: 'Extra Payment',
      yr:           'y',
      mo:           'm',
      cards:        'Your Cards',
      addCard:      'Add Card',
      removeCard:   'Remove Card',
      cardName:     'Card Name',
      combinedPayment: 'Combined Monthly Payment',
      extraBudget:  'Extra Monthly Budget',
      strategyComparison: 'Payoff Strategy Comparison',
      avalanche:    'Avalanche (Highest APR First)',
      snowball:     'Snowball (Lowest Balance First)',
      avalancheDesc:'Minimizes total interest paid',
      snowballDesc: 'Pays off smallest balance first for quick wins',
      debtFreeIn:   'Debt free in {months} months',
      totalInterestPaid: 'Total interest paid',
      payoffOrder:  'Payoff Order',
      noCards:      'Add at least one card to see projections.',
    },

    amex: {
      badge:        '⭐ American Express Referrals',
      heroTitle:    'Refer Friends. Earn Points.',
      heroBody:     'Share your Amex referral links and earn bonus Membership Rewards points or statement credits each time a friend is approved. It\'s one of the easiest ways to accelerate your rewards balance.',
      yourLink:     'Your Referral Link',
      linkDesc:     'Log in to your Amex account → "Refer a Friend" → paste your personal link below to share it easily.',
      linkPlaceholder: 'Paste your Amex referral link here…',
      copyBtn:      '📋 Copy Link',
      copiedBtn:    '✓ Copied!',
      linkTip:      'Tip: Your referral link is unique to you and the specific card. Get a separate link for each card you want to refer.',
      cardsTitle:   'Cards You Can Refer',
      cardsSub:     'You can only refer for cards you currently hold. Click "Refer a Friend" on amex.com after selecting the card.',
      welcomeOffer: 'Welcome Offer',
      welcomeBonus: 'Welcome Bonus:',
      bestFor:      'Best for:',
      referNote:    '',
      getLink:      'Get Your Referral Link →',
      tipsTitle:    '💡 Referral Tips',
      tips: [
        { icon:'🎯', title:'Get a unique link per card',  desc:'Each card you hold has its own referral link. Go to Refer a Friend on amex.com and select the specific card.' },
        { icon:'📣', title:'Share across channels',       desc:'Post to social media, text friends, or add to your email signature. More reaches = more approvals.' },
        { icon:'⏱', title:'Points post after approval',  desc:"Your referral bonus usually arrives within 8–12 weeks after your friend's application is approved." },
      ],
    },

    promo: {
      headline:     'Thinking About Opening a Credit Card?',
      subhead:      'See What We Use and Recommend',
      description:  'These are cards we personally use and trust. Apply through our referral links and you\'ll get a welcome bonus — plus help support this site at no cost to you.',
      welcomeBonus: 'Welcome Bonus',
      bestFor:      'Best for:',
      applyNow:     'Apply Now →',
      seeAll:       'See All Cards & Referral Links →',
    },

    personalLoan: {
      sub:             'Understand the true cost of personal loans and protect yourself from predatory lenders.',
      noteTitle:       '⚠ Our Personal Experience',
      noteBody:        'My wife came from Venezuela and was new to the US credit system. She took out a $5,000 personal loan at 35.95% APR for a car that turned out to be a rebuilt title. Nobody explained what that rate truly meant. The car is in a scrapyard. We are still paying the loan. We built this page so nobody else has to learn this lesson the hard way, especially immigrants and first-time borrowers. Know your rate before you sign anything.',
      calcTitle:       'Loan Calculator',
      loanAmount:      'Loan Amount',
      annualRate:      'Annual Interest Rate (APR)',
      termMonths:      'Loan Term (months)',
      monthly:         'Monthly Payment',
      totalInterest:   'Total Interest',
      totalCost:       'Total Cost',
      rateCheckTitle:  'Rate Reality Check',
      yourRate:        'Your Rate',
      rateExcellent:   'Excellent',
      rateGood:        'Good',
      rateFair:        'Fair',
      rateHigh:        'High',
      ratePredatory:   'PREDATORY',
      rateRange1:      '5–10%',
      rateRange2:      '10–15%',
      rateRange3:      '15–20%',
      rateRange4:      '20–30%',
      rateRange5:      '30%+',
      predatoryAlert:  '🚨 This is a predatory interest rate',
      predatoryDetail: 'At {rate}% APR, you will pay nearly as much in interest as you borrowed — sometimes more. This type of loan can trap you in a cycle of debt. Strongly consider credit unions, improving your credit score first, or borrowing from family before accepting these terms.',
      compTitle:       '$10,000 Loan — Side-by-Side Comparison',
      compSubtitle:    '60-month term',
      compAt:          'At {rate}%',
      compMonthly:     'Monthly Payment',
      compTotalInterest: 'Total Interest',
      compTotalCost:   'Total Cost',
      compSavings:     'vs 10%: the 35% rate costs {amt} extra in interest over 60 months',
      scoreTitle:      'Credit Score Impact',
      scoreSub:        'How your credit score affects the cost of your loan',
      scoreRange:      'Score Range',
      scoreRating:     'Rating',
      typicalAPR:      'Typical APR',
      monthlyAt:       'Monthly ({amount})',
      totalInterestAt: 'Total Interest',
      lendersTitle:    'Lender Comparison Guide',
      goodLendersTitle:'✅ Recommended Lenders',
      avoidTitle:      '🚫 Lenders to Avoid',
      redFlagsTitle:   '🚩 Red Flags to Watch For',
      avoidNote:       'These lenders often charge 35%+ APR and use aggressive marketing to target people with limited options. Read every contract carefully.',
      creditSavings:   'Improving to excellent credit could save you {savings}',
    },

    retirement: {
      sub:              'Project your nest egg and see if you\'re on track for a comfortable retirement.',
      inputs:           'Your Details',
      currentAge:       'Current Age',
      retirementAge:    'Retirement Age',
      currentSavings:   'Current Savings',
      monthlyContrib:   'Monthly Contribution',
      annualReturn:     'Expected Annual Return',
      annualReturnSub:  '(S&P 500 historical avg ~10%)',
      inflationRate:    'Inflation Rate',
      inflationSub:     'for real-value estimate',
      desiredIncome:    'Desired Annual Income in Retirement',
      desiredIncomeSub: 'in today\'s dollars',
      results:          'Projected at Retirement',
      projectedSavings: 'Projected Savings',
      atAge:            'at age {age}',
      yearsToRetire:    'Years to Retirement',
      totalContribs:    'Total Contributions',
      totalGrowth:      'Investment Growth',
      monthlyInRetirement: 'Est. Monthly Income',
      monthlyInRetirementSub: 'over {years} yr retirement',
      onTrack:          '✅ On Track',
      onTrackDesc:      'Your projected savings of {projected} exceeds your target of {target}. Great work!',
      offTrack:         '⚠ Needs Attention',
      offTrackDesc:     'You\'re {gap} short of your {target} target. Consider increasing contributions or adjusting your retirement age.',
      shortfall:        'Shortfall',
      surplus:          'Surplus',
      target:           'Savings Target',
      targetSub:        'to fund {years} yrs at {income}/yr',
      growthChart:      'Savings Growth Over Time',
      age:              'Age',
      savings:          'Savings',
      contributions:    'Contributions',
      growth:           'Growth',
      milestone25:      '25% Milestone',
      milestone50:      '50% Milestone',
      milestone75:      '75% Milestone',
      milestones:       'Key Milestones',
      retireIn:         'Retire in {n} years',
      globalSettings:   'Global Settings',
      accounts:         'Retirement Accounts',
      addAccount:       'Add Account',
      removeAccount:    'Remove Account',
      accountBalance:   'Current Balance',
      accountContrib:   'Monthly Contribution',
      accountReturn:    'Expected Annual Return',
      projectedAt:      'Projected at Age {age}',
      combinedTotal:    'Combined Total',
      accountsSummary:  'Account Breakdown',
      noAccounts:       'Add at least one account to see projections.',
      total:            'Total',
      socialSecurity:   'Monthly Social Security Estimate',
      socialSecuritySub:'reduces required portfolio size',
      stopAge:          'Contribution Stop Age',
      stopAgeHint:      'stop contributing at this age',
      newAccountName:   'Account name (e.g. TSP, Roth IRA)',
    },

    bills: {
      sub:          'Track your recurring bills, see what\'s due soon, and plan around your monthly obligations.',
      addBill:      'Add a Bill',
      billName:     'Bill Name',
      billNamePh:   'e.g. Rent, Electric, Insurance',
      amount:       'Amount',
      dueDate:      'Due Date',
      frequency:    'Frequency',
      category:     'Category',
      add:          'Add Bill',
      monthlyTotal: 'Monthly Total',
      annualTotal:  'Annual Total',
      yourBills:    'Your Bills',
      noBills:      'No bills added yet. Add your first recurring bill above.',
      dueSoon:      '⚠ Bills Due Within 7 Days',
      dueDateLabel: 'Due day',
      calTitle:     'Bill Calendar',
      freq_monthly:   'Monthly',
      freq_weekly:    'Weekly',
      freq_yearly:    'Yearly',
      freq_quarterly: 'Quarterly',
      cat_housing:       'Housing',
      cat_utilities:     'Utilities',
      cat_insurance:     'Insurance',
      cat_subscriptions: 'Subscriptions',
      cat_loans:         'Loans',
      cat_other:         'Other',
    },

    savings: {
      sub:          'Set savings goals, track your progress, and stay on track toward every milestone.',
      addGoal:      'Add a Goal',
      goalName:     'Goal Name',
      icon:         'Icon (emoji)',
      targetAmt:    'Target Amount',
      currentSaved: 'Current Savings',
      targetDate:   'Target Date',
      color:        'Color',
      add:          'Add Goal',
      yourGoals:    'Your Goals',
      noGoals:      'No goals yet. Add your first savings goal above.',
      complete:     '✅ Complete!',
      overdue:      'Overdue',
      onTrack:      'On Track',
      behind:       'Behind',
      daysLeft:     'days left',
      monthlyNeeded:'Monthly needed',
      totalSaved:   'Total Saved',
      totalTarget:  'Total Target',
      update:       'Update',
    },

    debt: {
      sub:          'Add all your debts and compare Avalanche vs Snowball payoff strategies to get debt-free faster.',
      addDebt:      'Add a Debt',
      debtName:     'Debt Name',
      balance:      'Current Balance',
      interestRate: 'Interest Rate (APR %)',
      minPayment:   'Minimum Payment',
      type:         'Debt Type',
      add:          'Add Debt',
      yourDebts:    'Your Debts',
      noDebts:      'No debts added yet. Add your first debt above.',
      totalDebt:    'Total Debt',
      minPayments:  'Total Min Payments',
      extraBudget:  'Extra Monthly Payment',
      avalanche:    'Avalanche (Highest Rate First)',
      snowball:     'Snowball (Lowest Balance First)',
      avalancheDesc:'Saves the most interest',
      snowballDesc: 'Quickest psychological wins',
      payoffDate:   'Debt-Free Date',
      totalInterest:'Total Interest',
      monthsToPayoff:'Months to Pay Off',
      payoffChart:  'Debt Payoff Over Time',
      strategyComparison: 'Strategy Comparison',
      type_credit:   'Credit Card',
      type_auto:     'Auto Loan',
      type_student:  'Student Loan',
      type_mortgage: 'Mortgage',
      type_personal: 'Personal Loan',
      type_other:    'Other',
    },

    emergency: {
      sub:           'Calculate how much you need in your emergency fund and see how long it will take to get there.',
      yourInfo:      'Your Information',
      monthlyExpenses:'Monthly Expenses',
      currentSavings: 'Current Emergency Savings',
      monthlyContrib: 'Monthly Contribution to Fund',
      fromBudget:    'Auto-loaded from your Budget Planner',
      manualOverride:'Leave blank to use your budget data',
      target3:       '3-Month Fund',
      target6:       '6-Month Fund',
      reached:       'Goal Reached!',
      timeline:      'Estimated time to reach goal',
      addContrib:    'Enter a monthly contribution to see timeline',
      enterExpenses: 'Enter your monthly expenses above, or add expenses in the Budget Planner to auto-load them.',
      tips:          'Emergency Fund Tips',
      tip1:          'Keep your emergency fund in a high-yield savings account, separate from your checking account.',
      tip2:          'Start with a $1,000 starter fund, then work toward 3 months, then 6 months.',
      tip3:          'Only use the fund for true emergencies: job loss, medical bills, major car or home repairs.',
    },

    subscriptions: {
      sub:          'Track all your subscriptions, spot spending leaks, and see your total monthly and annual cost.',
      addSub:       'Add a Subscription',
      subName:      'Subscription Name',
      cost:         'Cost',
      frequency:    'Billing Frequency',
      category:     'Category',
      add:          'Add Subscription',
      yourSubs:     'Your Subscriptions',
      noSubs:       'No subscriptions added yet. Add your first one above.',
      monthlyTotal: 'Monthly Total',
      annualTotal:  'Annual Total',
      byCategory:   'By Category',
      expensive:    'Priciest',
      freq_monthly:   'Monthly',
      freq_yearly:    'Yearly',
      freq_weekly:    'Weekly',
      freq_quarterly: 'Quarterly',
      cat_streaming:  'Streaming',
      cat_software:   'Software',
      cat_fitness:    'Fitness',
      cat_food:       'Food & Delivery',
      cat_news:       'News & Media',
      cat_gaming:     'Gaming',
      cat_other:      'Other',
    },

    military: {
      sub:               'Calculate your estimated military compensation including base pay, BAH, BAS, and Reserve drill pay.',
      yourInfo:          'Your Information',
      rank:              'Rank / Grade',
      yos:               'Years of Service',
      yosLabel:          'YOS',
      location:          'BAH Location',
      dependents:        'Dependents',
      withDep:           'With Dependents',
      withoutDep:        'Without Dependents',
      drillDays:         'Drill Periods per Month',
      drillDaysHint:     'Standard weekend drill = 4 periods',
      activeTab:         'Active Duty',
      reserveTab:        'Guard / Reserve',
      results:           'Pay Estimate',
      reserveResults:    'Reserve Pay Estimate',
      basePay:           'Basic Pay',
      bah:               'BAH',
      bas:               'BAS',
      totalComp:         'Total Monthly Compensation',
      taxNote:           'BAH & BAS are tax-free',
      drillPayMonth:     'Monthly Drill Pay',
      annualDrillPay:    'Annual Drill Pay',
      annualTraining:    'Annual Training Pay',
      totalAnnualReserve:'Total Annual Reserve Pay',
      excludesBah:       'Excludes BAH/BAS (paid during training)',
      periods:           'periods',
      perYear:           'per year',
      year:              'yr',
      payTable:          'Base Pay Table',
      annual:            'Annual',
      disclaimer:        'Estimates based on 2025 pay tables. Actual pay may vary. Special pays, allowances, and deductions not included.',
    },
  },

  /* ── SPANISH ───────────────────────────────────────────── */
  es: {
    nav: {
      brand:    'FinanceHub',
      car:      '🚗 Préstamo Auto',
      home:     '🏠 Préstamo Casa',
      budget:   '📝 Presupuesto',
      tax:      '💼 Ingreso Neto',
      cc:       '💳 Tarjeta Crédito',
      amex:        '⭐ Referencias',
      retirement:  '🏦 Jubilación',
      personalLoan: '📋 Préstamo Personal',
      groupLoans:       'Préstamos',
      groupPlanning:    'Planificación',
      groupIncome:      'Ingresos',
      groupInvestments: 'Inversiones',
      groupCards:       'Tarjetas',
      groupMilitary:    'Militar',
      bills:         '📅 Facturas',
      debt:          '💳 Deudas',
      emergency:     '🆘 Fondo de Emergencia',
      savings:       '🎯 Metas de Ahorro',
      subscriptions: '📱 Suscripciones',
      military:      '🎖 Paga Militar',
      langBtn:  'EN',
      langLabel:'English',
    },
    titles: {
      landing:       'Inicio',
      car:           'Calculadora de Préstamo de Auto',
      home:          'Calculadora de Préstamo Hipotecario',
      budget:        'Planificador de Presupuesto',
      tax:           'Ingreso Neto Después de Impuestos',
      cc:            'Pago de Tarjeta de Crédito',
      amex:          'Referencias de Tarjetas',
      retirement:    'Calculadora de Jubilación',
      personalLoan:  'Calculadora de Préstamo Personal',
      bills:         'Rastreador de Facturas',
      debt:          'Rastreador de Deudas',
      emergency:     'Calculadora de Fondo de Emergencia',
      savings:       'Metas de Ahorro',
      subscriptions: 'Rastreador de Suscripciones',
      military:      'Calculadora de Paga Militar',
    },
    footer: 'FinanceHub · Solo estimaciones educativas · No es asesoría financiera ·',

    landing: {
      badge:          '💰 Herramientas Financieras Gratuitas',
      heroTitle:      'Toma el Control de tus Finanzas',
      heroSub:        'Calculadoras gratuitas creadas por personas reales que aprendieron de sus errores. Sin anuncios ni ventas — solo herramientas honestas para tomar mejores decisiones.',
      heroCta1:       'Explorar Calculadoras',
      heroCta2:       'Nuestras Tarjetas Recomendadas',
      toolsTitle:     'Todas Nuestras Calculadoras',
      toolsSub:       'Encuentra la herramienta correcta para tu pregunta financiera.',
      openTool:       'Abrir calculadora',
      descCar:        'Calcula pagos mensuales, interés total y costo real de propiedad incluyendo seguro, mantenimiento y depreciación.',
      descHome:       'Modela tu pago hipotecario completo con impuestos, seguro y PMI — y ve crecer tu patrimonio.',
      descBudget:     'Tu centro completo de planificación financiera — registra ingresos, gastos, facturas, deudas, fondo de emergencia, metas de ahorro y suscripciones en un solo lugar.',
      descTax:        'Estima tu pago neto real después de impuestos federales, estatales y del FICA para cualquier ingreso.',
      descCc:         'Ve cuánto tiempo tarda en pagarse la deuda de tu tarjeta de crédito y cómo los pagos extra te ahorran miles.',
      descAmex:       'Tarjetas que usamos y en las que confiamos — aplica a través de nuestros enlaces y obtén un bono de bienvenida.',
      descRetirement: 'Proyecta tu fondo de retiro en múltiples cuentas y comprueba si vas por buen camino.',
      descPersonalLoan:  'Entiende el costo real de los préstamos personales, identifica prestamistas abusivos y compara tasas.',
      descBills:         'Rastrea tus facturas recurrentes con vista de calendario, categorías y alertas de vencimiento en 7 días.',
      descDebt:          'Compara las estrategias Avalancha y Bola de Nieve para salir de deudas más rápido.',
      descEmergency:     'Calcula tu meta de fondo de emergencia para 3 y 6 meses basada en tus gastos reales.',
      descSavings:       'Crea metas de ahorro con fechas objetivo, barras de progreso e indicadores de cumplimiento.',
      descSubscriptions: 'Lista todas tus suscripciones, ve el gasto mensual y anual total e identifica las más costosas.',
      descMilitary:      'Calcula la paga militar incluyendo sueldo base, BAH, BAS y paga de entrenamiento de reserva.',
      catLoans:        'Préstamos',
      catIncome:       'Ingresos e Impuestos',
      catPlanning:     'Planificación y Presupuesto',
      catInvestments:  'Inversiones',
      catCards:        'Tarjetas y Recompensas',
      trustFree:       '100% Gratis',
      trustPrivate:    'Totalmente Privado',
      trustNoAds:      'Sin Anuncios',
      trustNoSignup:   'Sin Registro',
      viewAll:         'Ver las 14 herramientas',
      viewFeatured:    'Mostrar solo destacados',
      cardsTitle:     'Tarjetas de Crédito que Usamos',
      cardsSub:       'Ganamos puntos y reembolso con tarjetas que recomendaríamos a cualquiera. Aplica con nuestros enlaces de referencia y obtén un bono de bienvenida.',
      aboutTitle:     'Construido por Personas Reales',
      aboutQuote:     '"Creamos FinanceHub porque sabemos lo que se siente cometer errores financieros costosos."',
      aboutBody1:     'Entre adaptarnos a un nuevo país, aprender el sistema de crédito en EE. UU. y descubrirlo todo sobre la marcha — ojalá hubiéramos tenido una herramienta así. Cada calculadora aquí es el recurso que necesitábamos y no encontramos.',
      aboutBody2:     'Ahora queremos ayudar a otros a tomar mejores decisiones financieras desde el principio. Todo es gratuito, privado y funciona completamente en tu navegador — sin registro, sin anuncios, sin trampa.',
      statTools:      'Calculadoras gratuitas',
      statFree:       'Gratis. Siempre.',
      statAds:        'Anuncios o ventas',
      ctaTitle:       '¿Listo para Tomar el Control?',
      ctaSub:         'Cada herramienta es gratuita y privada. Nada se almacena en un servidor. Empieza donde estés.',
      navHome:        'Inicio',
    },

    car: {
      sub:          'Calcula tu pago mensual y el costo total de la compra de un vehículo.',
      loanDetails:  'Detalles del Préstamo',
      vehiclePrice: 'Precio del Vehículo',
      downPayment:  'Pago Inicial',
      tradeIn:      'Valor de Intercambio',
      interestRate: 'Tasa de Interés',
      loanTerm:     'Plazo del Préstamo',
      months:       'meses',
      yr:           'año',
      yrs:          'años',
      paymentSummary: 'Resumen del Pago',
      monthlyPayment: 'Pago Mensual',
      forMonths:    'por {n} meses',
      loanAmount:   'Monto del Préstamo',
      totalInterest:'Interés Total',
      totalCost:    'Costo Total',
      includingDown:'incluyendo inicial',
      balanceOverTime: 'Saldo con el Tiempo',
      month:        'Mes',
      balance:      'Saldo',
      amortSched:   'Tabla de Amortización',
      hideTable:    'Ocultar Tabla',
      showTable:    'Ver Tabla',
      toggleHint:   'Muestra la tabla para ver el desglose mes a mes.',
      payment:      'Pago',
      principal:    'Capital',
      interest:     'Interés',
      extraPmt:     'Pago Mensual Adicional',
      earlyPayoff:  'Con Pago Adicional',
      monthsSaved:  'Meses Ahorrados',
      interestSaved:'Interés Ahorrado',
      paysOffIn:    'Se paga en {months} meses',
      vehicles:     'Tus Vehículos',
      addVehicle:   'Agregar Vehículo',
      removeVehicle:'Eliminar Vehículo',
      vehicleName:  'Nombre del Vehículo',
      combinedMonthly: 'Pago Mensual Combinado',
      noVehicles:   'Agrega al menos un vehículo para ver los cálculos.',

      lookupTitle:  'Búsqueda de Vehículo',
      lookupOptional:'(opcional)',
      newVehicle:   'Vehículo Nuevo',
      usedVehicle:  'Vehículo Usado',
      make:         'Marca',
      model:        'Modelo',
      trim:         'Versión',
      year:         'Año del Modelo',
      mileage:      'Kilometraje Actual',
      condition:    'Condición',
      condExcellent:'Excelente',
      condGood:     'Buena',
      condFair:     'Regular',
      condPoor:     'Mala',
      selectMake:   '— Seleccionar Marca —',
      selectModel:  '— Seleccionar Modelo —',
      selectTrim:   '— Seleccionar Versión —',
      msrpBase:     'MSRP Base',
      marketValue:  'Valor de Mercado Actual',
      futureValue:  'Valor al Terminar el Préstamo',
      depreciationDuring: 'Depreciación Durante el Préstamo',
      insuranceEst: 'Seguro Anual Est.',
      maintenanceEst:'Mantenimiento Anual Est.',
      perYear:      '/año',
      tcoTitle:     'Costo Total de Propiedad',
      tcoLoanCost:  'Pagos del Préstamo',
      tcoInsurance: 'Seguro (est.)',
      tcoInsuranceActual: 'Seguro (real)',
      tcoMaintenance:'Mantenimiento (est.)',
      tcoDeprec:    'Depreciación',
      tcoGrandTotal:'Gran Total',
      tcoOver:      'en {n} meses',
      upsideDown:   '⚠ Préstamo Invertido',
      upsideDownDesc:'El monto de tu préstamo ({loan}) supera el valor de mercado actual del auto ({value}). Debes más de lo que vale el auto.',
      actualInsuranceLabel:      'Mi seguro mensual real:',
      actualInsurancePlaceholder:'ej. 150',
      actualInsuranceUsed:       'Usando tu costo de seguro real',
    },

    home: {
      sub:            'Modela tu pago hipotecario incluyendo impuestos, seguro y PMI.',
      mortgageDetails:'Detalles Hipotecarios',
      homePrice:      'Precio de la Vivienda',
      downPayment:    'Pago Inicial',
      interestRate:   'Tasa de Interés',
      loanTerm:       'Plazo del Préstamo',
      years30:        '30 Años',
      years20:        '20 Años',
      years15:        '15 Años',
      years10:        '10 Años',
      propertyTax:    'Impuesto Predial /mes',
      insurance:      'Seguro /mes',
      hoa:            'HOA /mes',
      pmi:            'PMI /mes',
      pmiHint:        'Calculado automáticamente al 0.8% anual. Edita para cambiar.',
      ltvWarning:     'El LTV es {ltv}% — PMI agregado automáticamente. Se elimina al llegar al 80%.',
      extraPmt:       'Pago Mensual Adicional',
      withExtraPayoff:'Con Pago Adicional',
      monthsSaved:    'Meses Ahorrados',
      interestSaved:  'Interés Ahorrado',
      paysOffIn:      'Se paga en {months} meses',
      paymentBreakdown: 'Desglose del Pago Mensual',
      totalPITI:      'PITI Total /mes',
      pitiSub:        'capital + interés + depósito en garantía',
      piOnly:         'Solo C&I',
      loanAmount:     'Monto del Préstamo',
      totalInterest:  'Interés Total',
      equityGrowth:   'Crecimiento del Patrimonio',
      equity:         'Patrimonio',
      balance:        'Saldo',
      amortSched:     'Tabla de Amortización',
      hideTable:      'Ocultar Tabla',
      showTable:      'Ver Tabla',
      toggleHint:     'Muestra la tabla para ver el desglose mes a mes.',
      month:          'Mes',
      payment:        'Pago',
      principal:      'Capital',
      interest:       'Interés',
    },

    budget: {
      sub:           'Registra tus ingresos y gastos mensuales para saber a dónde va tu dinero.',
      monthlyIncome: 'Ingresos Mensuales',
      takeHome:      'Ingreso Neto (después de impuestos)',
      expenses:      'Gastos',
      addPlaceholder:'Agregar categoría…',
      add:           'Agregar',
      remove:        'Eliminar',
      summary:       'Resumen',
      totalExpenses: 'Gastos Totales',
      surplus:       'Superávit',
      deficit:       'Déficit',
      savingsRate:   'Tasa de Ahorro',
      savingsTarget: 'meta: 20%+',
      overspend:     'Estás gastando {amt}/mes más de lo que ganas. Revisa tus gastos.',
      breakdown:     'Desglose de Gastos',
      defaultCats:   ['Vivienda','Transporte','Comestibles','Servicios','Restaurantes','Salud','Entretenimiento','Ahorros','Ropa','Otros'],
      rule2030:      'Regla 50/30/20',
      needs:         'Necesidades',
      wants:         'Gustos',
      saves:         'Meta de Ahorro',
      needsHint:     'Vivienda, servicios, comestibles, salud, transporte',
      wantsHint:     'Restaurantes, entretenimiento, ropa, varios',
      savingsHint:   'Ahorro, inversiones, fondo de emergencia',
      ruleTarget:    'Meta',
      ruleActual:    'Real',

      tab_overview:  'Resumen',
      tab_expenses:  'Gastos',
      tab_calendar:  'Calendario',
      tab_networth:  'Patrimonio',
      totalSpent:    'Total Gastado',
      thisMonth:     'Este Mes',
      onTrack:       'Al día',
      overBudget:    'Sobre presupuesto',
      setBudget:     'Establecer límite',
      of:            'de',
      addCategory:   'Agregar Categoría',
      categoryName:  'Nombre de categoría',
      addExpense:    'Agregar Gasto',
      date:          'Fecha',
      description:   'Descripción',
      descPlaceholder:'ej. Renta, Gasolina, Netflix',
      amount:        'Monto',
      category:      'Categoría',
      recentExpenses:'Gastos Recientes',
      noExpenses:    'Sin gastos aún. Agrega uno en la pestaña Gastos.',
      insightsTitle: 'Análisis de Gastos',
      insightHousing:'Estás gastando {pct}% en vivienda, por encima del 30% recomendado.',
      insightDining: 'Restaurantes representan {pct}% de tus ingresos. Cocinar más puede ayudar.',
      insightSavings:'Estás ahorrando {pct}% de tus ingresos. La meta es el 20% o más.',
      insightGreat:  '¡Tus gastos se ven bien! Vas por buen camino en todas las categorías.',
      insightOverspent:'Excediste el presupuesto en {n} categoría(s). Revisa tus gastos.',
      netWorthTotal: 'Patrimonio Neto Total',
      assets:        'Activos',
      liabilities:   'Pasivos',
      assetName:     'ej. Cuenta de Ahorros',
      liabilityName: 'ej. Préstamo de Auto',
      total:         'Total',
      catNames: {
        housing:       'Vivienda',
        transport:     'Transporte',
        groceries:     'Comestibles',
        utilities:     'Servicios',
        dining:        'Restaurantes',
        healthcare:    'Salud',
        entertainment: 'Entretenimiento',
        savings:       'Ahorros',
        clothing:      'Ropa',
        other:         'Otros',
      },

      tab_bills:         'Facturas',
      tab_debt:          'Deudas',
      tab_emergency:     'Emergencia',
      tab_savings:       'Metas',
      tab_subscriptions: 'Suscs',
      tab_import:        'Importar CSV',
      importTitle:       'Importar Estado de Cuenta',
      importDesc:        'Sube un archivo CSV descargado de tu banco o tarjeta de crédito. Las transacciones se categorizan automáticamente y los duplicados se omiten.',
      dropzoneText:      'Haz clic o arrastra un archivo CSV o PDF aquí',
      supportedBanks:    'Chase · Bank of America · Capital One · Discover · American Express — CSV o PDF',
      detected:          'Banco Detectado',
      unknownBank:       'CSV Genérico',
      totalTransactions: 'Filas Totales',
      newTransactions:   'Nuevas',
      duplicatesSkipped: 'Duplicadas',
      importByCategory:  'Totales por Categoría a Importar',
      importPreview:     'Vista Previa de Transacciones',
      selectAll:         'Seleccionar Todo',
      deselectAll:       'Deseleccionar Todo',
      cancel:            'Cancelar',
      importBtn:         'Importar {n} Transacciones',
      importSuccess:     '{n} Transacciones Agregadas',
      importSuccessDesc: 'Tus transacciones han sido guardadas. Puedes verlas en la pestaña Gastos.',
      importAnother:     'Importar Otro Archivo',
      viewHistory:       'Ver Historial de Transacciones',
      parseError:        'No se pudo leer este archivo. Asegúrate de que sea un CSV o PDF válido exportado de un banco compatible.',
      notCsvError:       'Por favor sube un archivo .csv.',
      notFileError:      'Por favor sube un archivo .csv o .pdf de tu banco.',
      pdfNote:           'El análisis de PDF es aproximado. Si faltan transacciones, prueba exportar en formato CSV.',
      duplicate:         'Duplicada',
      history:           'Historial de Transacciones',
      transactions:      'transacciones',
      noHistory:         'Sin transacciones aún. Agrega una o importa un CSV de tu banco.',
      moreRows:          'más filas — desplaza la tabla para ver todas',
      importHowTo:       'Chase: Cuenta → Descargar actividad → CSV. BofA: Estados → Descargar → formato CSV. Capital One: Transacciones → Descargar. Discover: Administrar → Descargar Transacciones. Amex: Estados → Exportar.',
      orImportHint:      '¿Tienes un CSV de tu banco?',
      recentInCat:       'Recientes',
    },

    tax: {
      sub:          'Estima tu pago neto después de impuestos federales, estatales y del FICA para 2024.',
      incomeAndFiling:'Ingresos y Estado Civil',
      grossIncome:  'Ingreso Bruto Anual',
      filingStatus: 'Estado de Declaración',
      single:       'Soltero/a',
      married:      'Casado/a Declaración Conjunta',
      hoh:          'Jefe/a de Hogar',
      state:        'Estado',
      preTaxDed:    'Deducciones Pre-Impuestos',
      k401:         'Aportación 401(k)',
      hsa:          'Aportación HSA',
      otherPreTax:  'Otros Pre-Impuestos',
      takeHome:     'Pago Neto',
      annualNet:    'Neto Anual',
      monthly:      'Mensual',
      biWeekly:     'Quincenal',
      effectiveTax: 'Tasa Efectiva de Impuesto',
      ofGross:      'del ingreso bruto',
      fedTax:       'Impuesto Federal',
      socSec:       'Seguro Social',
      medicare:     'Medicare',
      stateTax:     'Impuesto Estatal',
      netTakeHome:  'Neto a Recibir',
      incomeBreakdown: 'Desglose de Ingresos',
      brackets:     'Tramos del Impuesto Federal (2025)',
      dualIncome:   'Hogar con Dos Ingresos',
      earner1:      'Ingreso 1',
      earner2:      'Ingreso 2',
      householdTotal:'Total del Hogar',
      enableDual:   'Agregar Segundo Ingreso',
      combinedNet:  'Neto Combinado',
      taxableIncome:'Ingreso gravable: {taxable} (después de deducción estándar de {deduction})',
      taxed:        'gravado',
      civilianMode: 'Civil',
      militaryMode: 'Pago Militar',
      milInputs:    'Información Militar',
      serviceType:  'Tipo de Servicio',
      activeDuty:   'Servicio Activo',
      guardReserve: 'Guardia / Reserva',
      milBahArea:   'Área de Costo de Destino',
      milPreTax:    'Deducciones Pre-Impuestos (TSP)',
      drillSchedule:'Calendario de Ejercicios',
      annualTrainingDays: 'Días de Entrenamiento Anual',
      milGrossPay:  'Pago Bruto Militar',
      taxableLabel: 'Gravable',
      taxFreeLabel: 'Libre de Impuestos',
      milTotalGross:'Compensación Bruta Total',
      milTaxNote:   'BAH y BAS son asignaciones libres de impuestos',
      milAnnualGross:'Bruto Anual',
      ofBasePay:    'del salario base',
      milOnBasePay: 'El impuesto federal se calcula solo sobre el salario base — BAH y BAS no se gravan',
    },

    cc: {
      sub:          'Mira cuánto tiempo tarda en pagarse una deuda de tarjeta de crédito y cómo ayudan los pagos extra.',
      cardDetails:  'Detalles de la Tarjeta',
      balance:      'Saldo Actual',
      apr:          'Tasa Anual (APR)',
      monthlyPmt:   'Pago Mensual',
      extraPmt:     'Pago Mensual Adicional',
      payoffScenarios: 'Escenarios de Pago',
      minPayment:   'Pago Mínimo (~2% del saldo)',
      payoffTime:   'Tiempo para Liquidar',
      totalInterest:'Interés Total',
      totalPaid:    'Total Pagado',
      atPayment:    'Con {amt}/mes',
      withExtra:    '✨ Con +{extra}/mes extra = {total}/mes',
      interestSaved:'Interés Ahorrado',
      monthsSaved:  'Meses Ahorrados',
      noPayment:    '¡El pago no cubre el interés!',
      lowPayment:   'El pago de {pmt} no cubre el cargo de interés de {interest}/mes. Aumenta tu pago.',
      keyStats:     'Datos Clave',
      dailyInterest:'Interés Diario',
      monthlyInterest:'Interés Mensual',
      annualInterest: 'Interés Anual',
      balanceOverTime:'Saldo con el Tiempo',
      basePayment:  'Pago Base',
      extraPayment: 'Pago Adicional',
      yr:           'a',
      mo:           'm',
      cards:        'Tus Tarjetas',
      addCard:      'Agregar Tarjeta',
      removeCard:   'Eliminar Tarjeta',
      cardName:     'Nombre de la Tarjeta',
      combinedPayment: 'Pago Mensual Combinado',
      extraBudget:  'Presupuesto Mensual Adicional',
      strategyComparison: 'Comparación de Estrategias',
      avalanche:    'Avalancha (Mayor APR Primero)',
      snowball:     'Bola de Nieve (Menor Saldo Primero)',
      avalancheDesc:'Minimiza el interés total pagado',
      snowballDesc: 'Paga el saldo más pequeño primero para victorias rápidas',
      debtFreeIn:   'Libre de deudas en {months} meses',
      totalInterestPaid: 'Interés total pagado',
      payoffOrder:  'Orden de Pago',
      noCards:      'Agrega al menos una tarjeta para ver las proyecciones.',
    },

    amex: {
      badge:        '⭐ Referencias de American Express',
      heroTitle:    'Recomienda Amigos. Gana Puntos.',
      heroBody:     'Comparte tus enlaces de referencia Amex y gana puntos de bonificación o créditos de estado de cuenta cada vez que un amigo sea aprobado. Es una de las formas más fáciles de acelerar tu saldo de recompensas.',
      yourLink:     'Tu Enlace de Referencia',
      linkDesc:     'Inicia sesión en tu cuenta Amex → "Recomienda a un Amigo" → pega tu enlace personal a continuación para compartirlo fácilmente.',
      linkPlaceholder: 'Pega tu enlace de referencia Amex aquí…',
      copyBtn:      '📋 Copiar Enlace',
      copiedBtn:    '✓ ¡Copiado!',
      linkTip:      'Consejo: Tu enlace de referencia es único para ti y para la tarjeta específica. Obtén un enlace distinto por cada tarjeta que desees referir.',
      cardsTitle:   'Tarjetas que Puedes Referir',
      cardsSub:     'Solo puedes referir tarjetas que actualmente tengas. Haz clic en "Recomienda a un Amigo" en amex.com después de seleccionar la tarjeta.',
      welcomeOffer: 'Oferta de Bienvenida',
      welcomeBonus: 'Bono de Bienvenida:',
      bestFor:      'Ideal para:',
      referNote:    '',
      getLink:      'Obtén tu Enlace de Referencia →',
      tipsTitle:    '💡 Consejos de Referencia',
      tips: [
        { icon:'🎯', title:'Un enlace único por tarjeta',   desc:'Cada tarjeta que tengas tiene su propio enlace de referencia. Ve a "Recomienda a un Amigo" en amex.com y selecciona la tarjeta específica.' },
        { icon:'📣', title:'Comparte en múltiples canales', desc:'Publica en redes sociales, envía mensajes a amigos o agrégalo a tu firma de correo. Más alcance = más aprobaciones.' },
        { icon:'⏱', title:'Los puntos llegan tras aprobación', desc:'Tu bono de referencia suele llegar entre 8 y 12 semanas después de que la solicitud de tu amigo sea aprobada.' },
      ],
    },

    retirement: {
      sub:              'Proyecta tu fondo de retiro y comprueba si vas por buen camino.',
      inputs:           'Tus Datos',
      currentAge:       'Edad Actual',
      retirementAge:    'Edad de Jubilación',
      currentSavings:   'Ahorros Actuales',
      monthlyContrib:   'Aportación Mensual',
      annualReturn:     'Rendimiento Anual Esperado',
      annualReturnSub:  '(promedio histórico S&P 500 ~10%)',
      inflationRate:    'Tasa de Inflación',
      inflationSub:     'para estimación en valor real',
      desiredIncome:    'Ingreso Anual Deseado en Jubilación',
      desiredIncomeSub: 'en dólares de hoy',
      results:          'Proyección al Retiro',
      projectedSavings: 'Ahorros Proyectados',
      atAge:            'a los {age} años',
      yearsToRetire:    'Años para Jubilarse',
      totalContribs:    'Aportaciones Totales',
      totalGrowth:      'Crecimiento por Inversión',
      monthlyInRetirement: 'Ingreso Mensual Est.',
      monthlyInRetirementSub: 'durante {years} años de retiro',
      onTrack:          '✅ En Buen Camino',
      onTrackDesc:      'Tu ahorro proyectado de {projected} supera tu meta de {target}. ¡Excelente trabajo!',
      offTrack:         '⚠ Requiere Atención',
      offTrackDesc:     'Te faltan {gap} para alcanzar tu meta de {target}. Considera aumentar tus aportaciones o ajustar tu edad de jubilación.',
      shortfall:        'Déficit',
      surplus:          'Superávit',
      target:           'Meta de Ahorro',
      targetSub:        'para {years} años a {income}/año',
      growthChart:      'Crecimiento del Ahorro con el Tiempo',
      age:              'Edad',
      savings:          'Ahorros',
      contributions:    'Aportaciones',
      growth:           'Crecimiento',
      milestone25:      'Hito 25%',
      milestone50:      'Hito 50%',
      milestone75:      'Hito 75%',
      milestones:       'Hitos Clave',
      retireIn:         'Jubilarse en {n} años',
      globalSettings:   'Configuración General',
      accounts:         'Cuentas de Jubilación',
      addAccount:       'Agregar Cuenta',
      removeAccount:    'Eliminar Cuenta',
      accountBalance:   'Saldo Actual',
      accountContrib:   'Aportación Mensual',
      accountReturn:    'Rendimiento Anual Esperado',
      projectedAt:      'Proyectado a los {age} años',
      combinedTotal:    'Total Combinado',
      accountsSummary:  'Desglose de Cuentas',
      noAccounts:       'Agrega al menos una cuenta para ver las proyecciones.',
      total:            'Total',
      socialSecurity:   'Estimado Mensual del Seguro Social',
      socialSecuritySub:'reduce el tamaño requerido del portafolio',
      stopAge:          'Edad de Parar Aportaciones',
      stopAgeHint:      'deja de aportar a esta edad',
      newAccountName:   'Nombre de cuenta (p.ej. TSP, Roth IRA)',
    },

    bills: {
      sub:          'Rastrea tus facturas recurrentes, ve qué vence pronto y planifica tus obligaciones mensuales.',
      addBill:      'Agregar Factura',
      billName:     'Nombre de la Factura',
      billNamePh:   'ej. Renta, Electricidad, Seguro',
      amount:       'Monto',
      dueDate:      'Fecha de Vencimiento',
      frequency:    'Frecuencia',
      category:     'Categoría',
      add:          'Agregar Factura',
      monthlyTotal: 'Total Mensual',
      annualTotal:  'Total Anual',
      yourBills:    'Tus Facturas',
      noBills:      'Sin facturas aún. Agrega tu primera factura arriba.',
      dueSoon:      '⚠ Facturas que Vencen en 7 Días',
      dueDateLabel: 'Día de vencimiento',
      calTitle:     'Calendario de Facturas',
      freq_monthly:   'Mensual',
      freq_weekly:    'Semanal',
      freq_yearly:    'Anual',
      freq_quarterly: 'Trimestral',
      cat_housing:       'Vivienda',
      cat_utilities:     'Servicios',
      cat_insurance:     'Seguro',
      cat_subscriptions: 'Suscripciones',
      cat_loans:         'Préstamos',
      cat_other:         'Otros',
    },

    savings: {
      sub:          'Establece metas de ahorro, sigue tu progreso y mantente en camino hacia cada hito.',
      addGoal:      'Agregar Meta',
      goalName:     'Nombre de la Meta',
      icon:         'Ícono (emoji)',
      targetAmt:    'Monto Objetivo',
      currentSaved: 'Ahorros Actuales',
      targetDate:   'Fecha Objetivo',
      color:        'Color',
      add:          'Agregar Meta',
      yourGoals:    'Tus Metas',
      noGoals:      'Sin metas aún. Agrega tu primera meta de ahorro arriba.',
      complete:     '✅ ¡Completado!',
      overdue:      'Vencida',
      onTrack:      'Al Día',
      behind:       'Atrasado',
      daysLeft:     'días restantes',
      monthlyNeeded:'Ahorro mensual necesario',
      totalSaved:   'Total Ahorrado',
      totalTarget:  'Total Objetivo',
      update:       'Actualizar',
    },

    debt: {
      sub:          'Agrega todas tus deudas y compara las estrategias Avalancha y Bola de Nieve para salir de deudas más rápido.',
      addDebt:      'Agregar Deuda',
      debtName:     'Nombre de la Deuda',
      balance:      'Saldo Actual',
      interestRate: 'Tasa de Interés (APR %)',
      minPayment:   'Pago Mínimo',
      type:         'Tipo de Deuda',
      add:          'Agregar Deuda',
      yourDebts:    'Tus Deudas',
      noDebts:      'Sin deudas aún. Agrega tu primera deuda arriba.',
      totalDebt:    'Deuda Total',
      minPayments:  'Pagos Mínimos Totales',
      extraBudget:  'Pago Mensual Extra',
      avalanche:    'Avalancha (Mayor Tasa Primero)',
      snowball:     'Bola de Nieve (Menor Saldo Primero)',
      avalancheDesc:'Ahorra más en intereses',
      snowballDesc: 'Victorias rápidas psicológicas',
      payoffDate:   'Fecha Libre de Deudas',
      totalInterest:'Interés Total',
      monthsToPayoff:'Meses para Liquidar',
      payoffChart:  'Liquidación de Deudas con el Tiempo',
      strategyComparison: 'Comparación de Estrategias',
      type_credit:   'Tarjeta de Crédito',
      type_auto:     'Préstamo de Auto',
      type_student:  'Préstamo Estudiantil',
      type_mortgage: 'Hipoteca',
      type_personal: 'Préstamo Personal',
      type_other:    'Otro',
    },

    emergency: {
      sub:           'Calcula cuánto necesitas en tu fondo de emergencia y cuánto tiempo tardarás en llegar.',
      yourInfo:      'Tu Información',
      monthlyExpenses:'Gastos Mensuales',
      currentSavings: 'Ahorros de Emergencia Actuales',
      monthlyContrib: 'Aportación Mensual al Fondo',
      fromBudget:    'Cargado automáticamente de tu Planificador',
      manualOverride:'Deja en blanco para usar tus datos del presupuesto',
      target3:       'Fondo de 3 Meses',
      target6:       'Fondo de 6 Meses',
      reached:       '¡Meta Alcanzada!',
      timeline:      'Tiempo estimado para alcanzar la meta',
      addContrib:    'Ingresa una aportación mensual para ver el cronograma',
      enterExpenses: 'Ingresa tus gastos mensuales arriba, o agrega gastos en el Planificador para cargarlos automáticamente.',
      tips:          'Consejos para el Fondo de Emergencia',
      tip1:          'Guarda tu fondo en una cuenta de ahorros de alto rendimiento, separada de tu cuenta de cheques.',
      tip2:          'Empieza con $1,000 como meta inicial, luego ve por 3 meses y después 6 meses.',
      tip3:          'Úsalo solo para emergencias reales: pérdida de empleo, facturas médicas, reparaciones mayores.',
    },

    subscriptions: {
      sub:          'Registra todas tus suscripciones, detecta gastos innecesarios y ve el costo mensual y anual total.',
      addSub:       'Agregar Suscripción',
      subName:      'Nombre de la Suscripción',
      cost:         'Costo',
      frequency:    'Frecuencia de Cobro',
      category:     'Categoría',
      add:          'Agregar Suscripción',
      yourSubs:     'Tus Suscripciones',
      noSubs:       'Sin suscripciones aún. Agrega la primera arriba.',
      monthlyTotal: 'Total Mensual',
      annualTotal:  'Total Anual',
      byCategory:   'Por Categoría',
      expensive:    'Más Costosa',
      freq_monthly:   'Mensual',
      freq_yearly:    'Anual',
      freq_weekly:    'Semanal',
      freq_quarterly: 'Trimestral',
      cat_streaming:  'Streaming',
      cat_software:   'Software',
      cat_fitness:    'Fitness',
      cat_food:       'Comida y Entrega',
      cat_news:       'Noticias y Medios',
      cat_gaming:     'Videojuegos',
      cat_other:      'Otros',
    },

    military: {
      sub:               'Calcula tu compensación militar estimada incluyendo sueldo base, BAH, BAS y paga de reserva.',
      yourInfo:          'Tu Información',
      rank:              'Rango / Grado',
      yos:               'Años de Servicio',
      yosLabel:          'años',
      location:          'Ubicación BAH',
      dependents:        'Dependientes',
      withDep:           'Con Dependientes',
      withoutDep:        'Sin Dependientes',
      drillDays:         'Períodos de Entrenamiento por Mes',
      drillDaysHint:     'Entrenamiento estándar de fin de semana = 4 períodos',
      activeTab:         'Activo',
      reserveTab:        'Guardia / Reserva',
      results:           'Estimación de Paga',
      reserveResults:    'Estimación de Paga de Reserva',
      basePay:           'Sueldo Base',
      bah:               'BAH',
      bas:               'BAS',
      totalComp:         'Compensación Mensual Total',
      taxNote:           'BAH y BAS están libres de impuestos',
      drillPayMonth:     'Paga de Entrenamiento Mensual',
      annualDrillPay:    'Paga Anual de Entrenamiento',
      annualTraining:    'Paga de Entrenamiento Anual (15 días)',
      totalAnnualReserve:'Total Anual de Reserva',
      excludesBah:       'Excluye BAH/BAS (se pagan durante entrenamiento)',
      periods:           'períodos',
      perYear:           'por año',
      year:              'año',
      payTable:          'Tabla de Sueldo Base',
      annual:            'Anual',
      disclaimer:        'Estimaciones basadas en tablas de paga 2025. La paga real puede variar. No incluye pagas especiales ni deducciones.',
    },

    promo: {
      headline:     '¿Estás pensando en abrir una tarjeta de crédito?',
      subhead:      'Conoce las que usamos y recomendamos',
      description:  'Estas son tarjetas que usamos y en las que confiamos personalmente. Aplica a través de nuestros enlaces de referencia y obtendrás un bono de bienvenida, además de apoyar este sitio sin costo para ti.',
      welcomeBonus: 'Bono de Bienvenida',
      bestFor:      'Ideal para:',
      applyNow:     'Aplicar Ahora →',
      seeAll:       'Ver Todas las Tarjetas y Referidos →',
    },

    personalLoan: {
      sub:             'Entiende el costo real de los préstamos personales y protégete de prestamistas abusivos.',
      noteTitle:       '⚠ Nuestra Experiencia Personal',
      noteBody:        'Mi esposa vino de Venezuela y era nueva en el sistema de crédito de Estados Unidos. Tomó un préstamo personal de $5,000 al 35.95% APR para un auto que resultó tener un título reconstruido. Nadie le explicó lo que realmente significaba esa tasa. El auto está en un depósito de chatarra. Todavía estamos pagando el préstamo. Construimos esta página para que nadie más tenga que aprender esta lección de la manera difícil, especialmente inmigrantes y personas que piden prestado por primera vez. Conoce tu tasa antes de firmar cualquier cosa.',
      calcTitle:       'Calculadora de Préstamo',
      loanAmount:      'Monto del Préstamo',
      annualRate:      'Tasa de Interés Anual (APR)',
      termMonths:      'Plazo del Préstamo (meses)',
      monthly:         'Pago Mensual',
      totalInterest:   'Interés Total',
      totalCost:       'Costo Total',
      rateCheckTitle:  'Verificación de Tasa',
      yourRate:        'Tu Tasa',
      rateExcellent:   'Excelente',
      rateGood:        'Buena',
      rateFair:        'Regular',
      rateHigh:        'Alta',
      ratePredatory:   'ABUSIVA',
      rateRange1:      '5–10%',
      rateRange2:      '10–15%',
      rateRange3:      '15–20%',
      rateRange4:      '20–30%',
      rateRange5:      '30%+',
      predatoryAlert:  '🚨 Esta es una tasa de interés abusiva',
      predatoryDetail: 'Con un APR de {rate}%, pagarás casi tanto en intereses como lo que pediste prestado — a veces más. Este tipo de préstamo puede atraparte en un ciclo de deudas. Considera fuertemente las cooperativas de crédito, mejorar tu puntaje crediticio primero, o pedir dinero prestado a un familiar antes de aceptar estas condiciones.',
      compTitle:       'Préstamo de $10,000 — Comparación',
      compSubtitle:    'Plazo de 60 meses',
      compAt:          'Al {rate}%',
      compMonthly:     'Pago Mensual',
      compTotalInterest: 'Interés Total',
      compTotalCost:   'Costo Total',
      compSavings:     'vs 10%: la tasa del 35% cuesta {amt} extra en intereses en 60 meses',
      scoreTitle:      'Impacto del Puntaje Crediticio',
      scoreSub:        'Cómo tu puntaje crediticio afecta el costo de tu préstamo',
      scoreRange:      'Rango de Puntaje',
      scoreRating:     'Calificación',
      typicalAPR:      'APR Típico',
      monthlyAt:       'Mensual ({amount})',
      totalInterestAt: 'Interés Total',
      lendersTitle:    'Guía de Comparación de Prestamistas',
      goodLendersTitle:'✅ Prestamistas Recomendados',
      avoidTitle:      '🚫 Prestamistas a Evitar',
      redFlagsTitle:   '🚩 Señales de Alerta',
      avoidNote:       'Estos prestamistas suelen cobrar 35%+ APR y usan marketing agresivo para dirigirse a personas con opciones limitadas. Lee cada contrato con cuidado.',
      creditSavings:   'Mejorar a crédito excelente podría ahorrarte {savings}',
    },
  },
};
